services:
  - type: web
    name: shuttle-monitoring-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT src.main:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: shuttle-monitoring-db
          property: connectionString
    healthCheckPath: /api/health

databases:
  - name: shuttle-monitoring-db
    databaseName: shuttle_monitoring
    user: shuttle_user
    plan: free

